Répondez à la question suivante en se basant uniquement sur le contexte donné,
si vous renconrez des questions dont les réponses ne figurent pas dans le contexte,
veuillez répondre "Je ne sais pas". Ne faites pas de recherche sur internet.
Ne détaillez pas votre réponse, une réponse simple suffit.
Répondez avec la langue dans laquelle la question est posée. N'oubliez pas, j'ai dit la langue dans laquelle la question est posée!!!!!
<context>
{context}
</context>
<userQuery>
{question}
</userQuery>